//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FestPicks.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class moviesdetail
    {
        public long Id { get; set; }
        public string FestivalShortName { get; set; }
        public string FestivalFullName { get; set; }
        public string Award { get; set; }
        public string Category { get; set; }
        public string Placing { get; set; }
        public string Title { get; set; }
        public string AwardYear { get; set; }
        public string ReleaseYear { get; set; }
        public string Rated { get; set; }
        public string Released { get; set; }
        public string Runtime { get; set; }
        public string Genre { get; set; }
        public string Director { get; set; }
        public byte[] Writer { get; set; }
        public string Actors { get; set; }
        public byte[] Description { get; set; }
        public string Language { get; set; }
        public string Country { get; set; }
        public string PosterLink { get; set; }
        public string Metascore { get; set; }
        public string Rating { get; set; }
        public string imdbVotes { get; set; }
        public string imdbID { get; set; }
        public string TrailerLink { get; set; }
        public string MovieLink { get; set; }
        public byte[] YoutubeEmbeddedCode { get; set; }
        public byte[] Payload { get; set; }
        public bool HighlightFilm { get; set; }
        public int festival_id { get; set; }
        public bool DisplayFilm { get; set; }
        public string AmazonLinkRent { get; set; }
    
        public virtual festivaldetail festivaldetail { get; set; }
    }
}
